#include "../headers/board.h"

#define DEBUGGIN_MODE 0
#define DEBUGGIN_MODE_CARD 0 //DONE
#define DEBUGGIN_MODE_DISPLAY 0 //DONE
#define DEBUGGIN_MODE_ENCODER 0 //Done
#define DEBUGGIN_MODE_LED 0 //DONE
#define DEBUGGIN_MODE_PV 1
#define DEBUGGIN_MODE_PWM 0
#define DEBUGGIN_MODE_SYSTICK 0
#define DEBUGGIN_MODE_TIMER 0
